source 'https://rubygems.org'
ruby '1.9.3'

gem 'activerecord'
gem 'ansi'
gem 'i2c'
gem 'rake'
gem 'rrd-ffi'
gem 'rubygsm', git: 'https://github.com/borischernov/rubygsm.git'
gem 'rufus-scheduler'
gem 'serialport'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-formhelpers-ng'
gem 'sqlite3'
gem 'thin'
