source 'https://rubygems.org'
ruby '1.9.3'

gem 'activerecord'
gem 'ansi'
gem 'rake'
gem 'rufus-scheduler'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-formhelpers-ng'
gem 'sqlite3'
gem 'thin'
gem 'wiringpi'
