#
# Default settings for Raspberry Pi
#
readings_retention_days: 30       # Retention interval for sensor readings
local_console: '1m'               # Refresh interval for local console (false to disable)
network_reset_gpio: 7             # GPIO pin used for network settings reset
# ESP8266 connection parameters
esp8266:
  serial_port: '/dev/ttyAMA0'
  serial_speed: 115200
  pin_reset: 0 
  pin_gpio0: 1
# Local sensors parameters
local_sensors_poll: '2m'          # Local sensors poll frequency (false to disable)
poll_1wire: true                  # Poll 1wire sensors (true / false)
poll_i2c: 1                       # Poll i2c sensors (bus number / false to disable)
